#!/usr/bin/python3
""" State Module for HBNB project """
from models.base_model import BaseModel, Base
from sqlalchemy.orm import relationship
from sqlalchemy import Column, String

class State(BaseModel, Base):
    """ State class """
    __tablename__ = 'states'

    name = Column(String(128), nullable=False)
    
    if storage.__class.__name__ == 'DBStorage':
        from models.__init__ import storage
        cities = relationship("City", cascade="all, delete", backref="state")

    elif storage.__class__name__ == 'FileStorage':
        @property
        def cities(self):
            """"""

            from models.__init__ import storage
            city_list = []
            for city in storage.all("City").values():
                if city.state_id == self.id:
                    city_list.append(city)
            return city_list
